version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: anime_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl:
    build: .
    command: python src/main.py
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: password
      DB_NAME: anime_db

volumes:
  postgres_data: